"""empty message

Revision ID: bd3388189124
Revises: 54947f1c4a22
Create Date: 2022-08-05 21:31:22.633848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd3388189124'
down_revision = '54947f1c4a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    op.drop_column('users', 'name')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
